name: d2venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - datasets
  - gensim
  - ipykernel
  - ipywidgets
  - matplotlib
  - matplotlib-inline
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - tqdm
  - umap-learn
  - pip